# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
# config/packages/scheb_2fa.yaml
    email:
        enabled: true
        sender_email: no-reply@taf-hunt.fr
        sender_name: John coffee  # Optional